In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [3]:
text = '해보지 않으면 해낼 수 없다.'

In [6]:
result = text_to_word_sequence(text)
print("원문: ", text)
print("토큰화: ", result) # 토큰, 코퍼스(corpus)

원문:  해보지 않으면 해낼 수 없다.
토큰화:  ['해보지', '않으면', '해낼', '수', '없다']


In [8]:
# 단어 빈도수 세기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

# 토크나이즈 사용법

In [9]:
# 문장 토큰화 하기
token = Tokenizer(lower=False)
token.fit_on_texts(docs)

In [10]:
print('단어 카운트: ', token.word_counts)

단어 카운트:  OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [11]:
print('문장 카운트: ', token.document_count)

문장 카운트:  3


In [12]:
print('각 단어가 몇 개의 문장에 포함되어 있는가? ', token.word_docs)

각 단어가 몇 개의 문장에 포함되어 있는가?  defaultdict(<class 'int'>, {'단어를': 1, '토큰화': 1, '텍스트의': 2, '먼저': 1, '나누어': 1, '합니다': 1, '각': 1, '딥러닝에서': 2, '토큰화해야': 1, '인식됩니다': 1, '단어로': 1, '있습니다': 1, '사용할': 1, '토큰화한': 1, '결과는': 1, '수': 1})


In [13]:
print('각 단어에 매겨진 인덱스: ', token.word_index)

각 단어에 매겨진 인덱스:  {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


# 단어의 원-핫 인코딩

In [14]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'
token = Tokenizer(lower=False)
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [16]:
# 단어를 벡터로 변환
x = token.texts_to_sequences([text])

In [17]:
len(token.word_index)

6

In [18]:
# 인덱스에 1을 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1 # +1 해주는 이유는 결과 앞에 0 안들어가서 잘려서 들어감

In [19]:
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


# 텍스트를 읽고 긍정, 부정 예측하기

In [20]:
docs = ['너무 재밌네요', '최고에요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.',
       '한번 더 보고싶네요', '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

# 긍정리뷰는 1, 부정리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [21]:
# 토큰화
token = Tokenizer(lower=False)
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [22]:
# 원핫인코딩(벡터로 변환)
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [24]:
# 패딩 추가 pad_sequences(데이터, 가장 긴 문장의 길이)
padded_x = pad_sequences(x, 4)
print("패딩 결과", padded_x)

패딩 결과 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [25]:
# 임베딩에 입력된 단어의 수 지정
word_size = len(token.word_index) + 1

In [26]:
# 단어 임베딩을 포함해서 딥러닝 모델 생성
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
history = model.fit(padded_x, classes, epochs=20)
print('Accuracy: ', model.evaluate(padded_x, classes)[1])

Epoch 1/20
1/1 [==============================] - 2s 2s/step - loss: 0.7027 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.7005 - accuracy: 0.4000
Epoch 3/20
1/1 [==============================] - 0s 0s/step - loss: 0.6982 - accuracy: 0.4000
Epoch 4/20
1/1 [==============================] - 0s 0s/step - loss: 0.6960 - accuracy: 0.4000
Epoch 5/20
1/1 [==============================] - 0s 0s/step - loss: 0.6938 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 0s/step - loss: 0.6915 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6893 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 0s/step - loss: 0.6871 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6849 - accuracy: 0.6000
Epoch 10/20
1/1 [==============================] - 0s 821us/step - loss: 0.6827 - accuracy: 0.6000
Epoch 11/20
1/1 [==========================