# 컨텐츠 기반 추천시스템 - TMDB 5000 Movie Dataset

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/tmdb_5000_movies.csv")
data.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [4]:
data['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [5]:
# [{}] 리스트 안에 딕셔너리 있으면 json 파일이구나(오브젝트)
print(type(data['genres'][0]))
# str이면 json으로 바꿔주기!

<class 'str'>


In [6]:
import json

In [7]:
test = json.loads(data['genres'][0])
test

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [8]:
# 방법 1
for i in test:
    print(list(i.values())[1])

Action
Adventure
Fantasy
Science Fiction


In [9]:
# 방법 2
for i in test:
    print(i['name'])

Action
Adventure
Fantasy
Science Fiction


In [10]:
# 다음단계
genre = []
for i in test:
    genre.append(i['name'])

In [11]:
genre = " ".join(genre)
genre

'Action Adventure Fantasy Science Fiction'

In [12]:
data['genres']= data['genres'].apply(json.loads)

In [13]:
data['genres'] = data['genres'].apply(lambda x: [i['name'] for i in x])

In [14]:
data['genres'] = data['genres'].apply(lambda x: " ".join(x))

In [15]:
data.head(2)

budget                                    genres  \
0  237000000  Action Adventure Fantasy Science Fiction   
1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [16]:
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

* 바꿔줘야할거 리스트로 만들어서 반복문 넣어주면 끝
* genres, keywords, production_companies, production_countries, spoken_languages

In [17]:
for col in ['keywords', 'production_companies', 'production_countries', 'spoken_languages']:
    data[col] = data[col].apply(json.loads)
    data[col] = data[col].apply(lambda x: [i['name'] for i in x])
    data[col] = data[col].apply(lambda x: " ".join(x))

In [18]:
data.head(2)

budget                                    genres  \
0  237000000  Action Adventure Fantasy Science Fiction   
1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  Ingenious Film Partners Twentieth Century Fox ...   
1  Walt Disney Pictures Jerry Bruckheimer Films S...   

                      production_countries release_date     revenue  runtime  \
0  United States of America United Kingdom   2009-12-10  2787965087    162.0   
1                 United States of America   2007-05-19   961000000    169.0   

  spoken_languages    status                                         tagline  \
0  English Español  Released                     Enter the World of Pandora.   
1          English  Released  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [19]:
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [20]:
# 다 하기는 너무 많으니까 몇개만 골라서 해보기
data = data[['id', 'title', 'genres', 'vote_average', 'popularity', 'keywords', 'overview']]
data.head(2)

id                                     title  \
0  19995                                    Avatar   
1    285  Pirates of the Caribbean: At World's End   

                                     genres  vote_average  popularity  \
0  Action Adventure Fantasy Science Fiction           7.2  150.437577   
1                  Adventure Fantasy Action           6.9  139.082615   

                                            keywords  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...

* genres의 단어를 벡터화해서 코사인 유사도를 통해 비슷한 장르를 가진 행을 찾고 유사도가 높은 행을 기준으로 내림차순 정렬

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
cv = CountVectorizer(ngram_range=(1,2))
genre_mat = cv.fit_transform(data['genres'])
print(genre_mat)

  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1
  (1, 0)	1
  (1, 16)	1
  (1, 124)	1
  (1, 24)	1
  (1, 125)	1
  (2, 0)	1
  (2, 16)	1
  (2, 1)	1
  (2, 64)	1
  (2, 20)	1
  (3, 0)	1
  (3, 64)	1
  (3, 90)	1
  (3, 234)	1
  (3, 4)	1
  (3, 68)	1
  :	:
  (4796, 90)	1
  (4796, 234)	1
  (4796, 106)	1
  (4796, 144)	1
  (4797, 234)	1
  (4797, 153)	1
  (4797, 157)	1
  (4798, 0)	1
  (4798, 64)	1
  (4798, 234)	1
  (4798, 4)	1
  (4798, 78)	1
  (4799, 44)	1
  (4799, 214)	1
  (4799, 58)	1
  (4800, 90)	1
  (4800, 44)	1
  (4800, 214)	1
  (4800, 104)	1
  (4800, 50)	1
  (4800, 250)	1
  (4800, 182)	1
  (4800, 251)	1
  (4800, 229)	1
  (4802, 80)	1


In [23]:
genre_mat.shape

(4803, 276)

코사인 유사도를 사용해 genre_mat의 유사도를 산출 후 genre_sim에 저장
* 비슷한 장르 영화를 찾기 위해 계산
* 코사인 유사도는 주로 문자, 문서의 유사도 계산에 사용됨

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
# 여기서 1은 자기자신?
genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:2])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]]


In [26]:
data['genres'][:4]

0    Action Adventure Fantasy Science Fiction
1                    Adventure Fantasy Action
2                      Action Adventure Crime
3                 Action Crime Drama Thriller
Name: genres, dtype: object

In [27]:
# argsort는 숫자가 작은거부터 인덱스를 주는것
a = np.array([1.5, 0.2, 4.2, 2.5])
s = a.argsort()
print(s)

[1 0 3 2]


In [28]:
print(s[::-1]) # 역순

[2 3 0 1]


In [29]:
sorted_genre_sim = genre_sim.argsort()[:, ::-1]

In [30]:
sorted_genre_sim[:1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401]], dtype=int64)

In [31]:
data.loc[0]

id                                                          19995
title                                                      Avatar
genres                   Action Adventure Fantasy Science Fiction
vote_average                                                  7.2
popularity                                             150.437577
keywords        culture clash future space war space colony so...
overview        In the 22nd century, a paraplegic Marine is di...
Name: 0, dtype: object

In [32]:
data.loc[3494]

id                                                          27549
title                   Beastmaster 2: Through the Portal of Time
genres                   Action Adventure Fantasy Science Fiction
vote_average                                                  4.6
popularity                                               1.478505
keywords        based on novel time travel sequel psychotronic...
overview        Mark Singer returns as Dar, the warrior who ca...
Name: 3494, dtype: object

In [33]:
# 영화 인덱스 추출
print(data[data['title']=='Superman'].index.values)

[813]


In [34]:
# 이 번호에 해당하는 index추출하면 비슷한 장르 뽑혀서 나옴
data.iloc[sorted_genre_sim[813, : (5)].reshape(-1)]

id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   

                                        genres  vote_average  popularity  \
0     Action Adventure Fantasy Science Fiction           7.2  150.437577   
3494  Action Adventure Fantasy Science Fiction           4.6    1.478505   
813   Action Adventure Fantasy Science Fiction           6.9   48.507081   
870   Action Adventure Fantasy Science Fiction           6.5   30.515175   
46    Action Adventure Fantasy Science Fiction           7.5  118.078691   

                                               keywords  \
0     culture clash future space war space colony so...   
3494  based on novel time travel sequel psychotronic...   
813   saving the world journalist dc comics crime fi...   
870   saving the world dc comics sequel superhero ba...   
46    1970s mutant time travel marvel comic based on...   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
3494  Mark Singer returns as Dar, the warrior who ca...  
813   Mild-mannered Clark Kent works as a reporter a...  
870   Three escaped criminals from the planet Krypto...  
46    The ultimate X-Men ensemble fights a war for t...

In [35]:
def find_sim_movie(df, sorted_genre_sim, title_name, top_n=10):
    title_movie = df[df['title']== title_name]
    title_index = title_movie.index.values
    similar_indexes = sorted_genre_sim[title_index, : (top_n)]
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]

In [36]:
find_sim_movie(data, sorted_genre_sim, 'Avatar', 10)

[[   0 3494  813  870   46   14 1296 1652  419  420]]


id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   
14     49521                               Man of Steel   
1296    9531                               Superman III   
1652   14164                       Dragonball Evolution   
419     8247                                     Jumper   
420    11253                Hellboy II: The Golden Army   

                                                 genres  vote_average  \
0              Action Adventure Fantasy Science Fiction           7.2   
3494           Action Adventure Fantasy Science Fiction           4.6   
813            Action Adventure Fantasy Science Fiction           6.9   
870            Action Adventure Fantasy Science Fiction           6.5   
46             Action Adventure Fantasy Science Fiction           7.5   
14             Action Adventure Fantasy Science Fiction           6.5   
1296    Comedy Action Adventure Fantasy Science Fiction           5.3   
1652  Action Adventure Fantasy Science Fiction Thriller           2.9   
419                   Adventure Fantasy Science Fiction           5.9   
420                   Adventure Fantasy Science Fiction           6.5   

      popularity                                           keywords  \
0     150.437577  culture clash future space war space colony so...   
3494    1.478505  based on novel time travel sequel psychotronic...   
813    48.507081  saving the world journalist dc comics crime fi...   
870    30.515175  saving the world dc comics sequel superhero ba...   
46    118.078691  1970s mutant time travel marvel comic based on...   
14     99.398009  saving the world dc comics superhero based on ...   
1296   22.164202  saving the world dc comics super computer iden...   
1652   21.677732  karate superhero revenge dragon duringcreditss...   
419    21.218000  adolescence based on novel loss of child fight...   
420    58.579760  auction northern ireland resignation superhero...   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
3494  Mark Singer returns as Dar, the warrior who ca...  
813   Mild-mannered Clark Kent works as a reporter a...  
870   Three escaped criminals from the planet Krypto...  
46    The ultimate X-Men ensemble fights a war for t...  
14    A young boy learns that he has extraordinary p...  
1296  Aiming to defeat the Man of Steel, wealthy exe...  
1652  The young warrior Son Goku sets out on a quest...  
419   David Rice is a man who knows no boundaries, a...  
420   In this continuation to the adventure of the d...

In [37]:
import joblib

In [39]:
joblib.dump(data,"./movie_data")

['./movie_data']

In [40]:
joblib.dump(sorted_genre_sim,"./movie_similarity")

['./movie_similarity']